### ISSUE TITLE
vulnerability in node dependency

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#15]
@rdebeasi the suggested resolution below is quite a bit newer than what we have in our package.json. can we upgrade?

![uncontained-vulnerability](https://user-images.githubusercontent.com/4500758/39457550-7b62b9f2-4cbc-11e8-9920-16d20879b493.png)

**Comment by rdebeasi** [comment]
Looks like this is a [problem with node-sass v4](https://github.com/sass/node-sass/issues/2355), which is a dependency of the gulp-sass package that we're using. The problem has been fixed in v5.

We'll probably need to wait for the node-sass folks to either release v5 or backport the fix to v4. The good news is that this dependency is used only when building the theme, so the impact of the vulnerability is most likely limited.
