### ISSUE TITLE
Repository Review and Feedback

### ISSUE THREAD

**Issue by mm7259** [redhat-cop/uncontained.io#218]
In order to make it easier for new contributors to get started, there should be example article ASCII Docs with boilerplate structure

**Comment by chadmf** [comment]
Let me take this one.

**Comment by chadmf** [comment]
Initial thoughts for improvement in the github code side:

1. Move roadmap to a project like github does here: https://github.com/github/roadmap/projects/1
2. Move how to contribute closer to the top, it's a bit buried in the README
3. Update local development. We should try and make this more consumable for people to just contribute via ADOC. 
4. Move https://github.com/redhat-cop/uncontained.io/blob/master/docs/new_articles.adoc to front page, or link it from front page.
5. The OpenShift Docs are really old
6. Local dev section make sure user is in the top level directory of the project after they clone.

For the website itself having pages on contribution rendered instead of in github may be easier for non developers.
