### ISSUE TITLE
Require only 1 approver

### ISSUE THREAD

**Issue by rdebeasi** [redhat-cop/uncontained.io#65]
Hello! I'd like to propose that we require only 1 approver for PRs in this repo. CoP projects typically require two approvers before a PR is merged, but I think something like uncontained.io has lower complexity and bugs in this repo carry a lower risk compared to something like the applier.

If there's consensus, someone with admin rights (i.e., not me :stuck_out_tongue_closed_eyes: ) could change the appropriate setting in GitHub.

**Comment by rdebeasi** [comment]
CC @redhat-cop/cant-contain-this-mergers

**Comment by etsauer** [comment]
@rdebeasi this repo is actually the ONLY CoP repo that I know of that requires two approvals to merge. In the case of Theme/CSS changes, I agree with you, I think we should only require 1 approval. However, for content submissions, we require two changes because (when the site is live) a merge directly results in a production push. We've had times in the past, before we implemented the 2-approver policy when a contributed article was merged which contained customer data. We had to deal with GitHUb support to get that data expunged from our history.

Perhaps this is something we can think on some more, as I don't believe that there is a way to implement conditionals in your merge policy. Perhaps we should consider splitting the theme and the content into separate repos, but that might make testing more difficult.

**Comment by etsauer** [comment]
Another consideration is that we could temporarily remove the two approver policy until the site is live, so as to accelerate development until then.

**Comment by etsauer** [comment]
I've reduced the required approvers to 1 for now. let's see how it goes.

**Comment by rdebeasi** [comment]
Awesome, thank you!
